const pool = require('../config/database');
const PDFDocument = require('pdfkit');

async function classOverview(req, res, next) {
  try {
    const facultyId = req.user.sub;
    const students = await pool.query(`SELECT u.id, u.display_name, u.email, COALESCE(ROUND(AVG(tp.completion_percent), 0), 0)::integer AS completion_percent, MAX(u.last_login_at) AS last_active FROM class_members cm JOIN faculty_classes fc ON fc.id = cm.class_id JOIN users u ON u.id = cm.student_id LEFT JOIN topic_progress tp ON tp.user_id = u.id WHERE fc.faculty_id = $1 GROUP BY u.id, u.display_name, u.email ORDER BY u.display_name`, [facultyId]);
    const scores = await pool.query(`SELECT COALESCE(ROUND(AVG(qa.score), 1), 0) AS average_score, COUNT(DISTINCT qa.user_id)::integer AS total_students FROM quiz_attempts qa JOIN class_members cm ON cm.student_id = qa.user_id JOIN faculty_classes fc ON fc.id = cm.class_id WHERE fc.faculty_id = $1`, [facultyId]);
    const misconceptions = await pool.query(`SELECT sm.misconception_key, COUNT(*)::integer AS occurrences FROM student_misconceptions sm JOIN class_members cm ON cm.student_id = sm.user_id JOIN faculty_classes fc ON fc.id = cm.class_id WHERE fc.faculty_id = $1 GROUP BY sm.misconception_key ORDER BY occurrences DESC LIMIT 8`, [facultyId]);
    return res.json({ totalStudents: students.rows.length, completionPercent: students.rows.length ? Math.round(students.rows.reduce((sum, student) => sum + student.completion_percent, 0) / students.rows.length) : 0, averageScore: Number(scores.rows[0]?.average_score || 0), students: students.rows, commonMisconceptions: misconceptions.rows });
  } catch (error) { return next(error); }
}

async function listQuestions(req, res, next) {
  try { const result = await pool.query('SELECT * FROM question_bank WHERE faculty_id = $1 ORDER BY updated_at DESC', [req.user.sub]); return res.json({ questions: result.rows }); } catch (error) { return next(error); }
}
async function saveQuestion(req, res, next) {
  try { const { id, topic_slug, prompt, question_type, options = [], answer, difficulty = 'standard' } = req.body || {}; if (!prompt || !topic_slug || !question_type) return res.status(422).json({ error: 'topic_slug, prompt, and question_type are required' }); const result = id ? await pool.query('UPDATE question_bank SET topic_slug=$1, prompt=$2, question_type=$3, options=$4, answer=$5, difficulty=$6, updated_at=CURRENT_TIMESTAMP WHERE id=$7 AND faculty_id=$8 RETURNING *', [topic_slug, prompt, question_type, JSON.stringify(options), answer, difficulty, id, req.user.sub]) : await pool.query('INSERT INTO question_bank (faculty_id, topic_slug, prompt, question_type, options, answer, difficulty) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *', [req.user.sub, topic_slug, prompt, question_type, JSON.stringify(options), answer, difficulty]); return res.json({ question: result.rows[0] }); } catch (error) { return next(error); }
}
async function deleteQuestion(req, res, next) { try { await pool.query('DELETE FROM question_bank WHERE id=$1 AND faculty_id=$2', [req.params.id, req.user.sub]); return res.status(204).send(); } catch (error) { return next(error); } }
async function announce(req, res, next) { try { if (!req.body?.message?.trim()) return res.status(422).json({ error: 'Announcement message is required' }); const result = await pool.query('INSERT INTO announcements (faculty_id, message) VALUES ($1,$2) RETURNING *', [req.user.sub, req.body.message.trim()]); return res.status(201).json({ announcement: result.rows[0] }); } catch (error) { return next(error); } }
async function csvReport(req, res, next) { try { const overview = await classOverviewData(req.user.sub); const rows = [['student_name', 'email', 'completion_percent', 'last_active'], ...overview.students.map((student) => [student.display_name, student.email, student.completion_percent, student.last_active || ''])]; res.type('text/csv').attachment('class-progress.csv').send(rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n')); } catch (error) { return next(error); } }
async function pdfReport(req, res, next) { try { const overview = await classOverviewData(req.user.sub); const document = new PDFDocument({ margin: 48 }); res.type('application/pdf').attachment('class-progress.pdf'); document.pipe(res); document.fontSize(20).text('Quantum Atlas - Class Progress Report'); document.moveDown().fontSize(11).text(`Generated ${new Date().toLocaleString()}`); document.moveDown(); overview.students.forEach((student) => document.text(`${student.display_name} | ${student.email} | ${student.completion_percent}% complete | Last active: ${student.last_active || 'Never'}`)); document.end(); } catch (error) { return next(error); } }
async function classOverviewData(facultyId) { const result = await pool.query(`SELECT u.display_name, u.email, COALESCE(ROUND(AVG(tp.completion_percent), 0), 0)::integer AS completion_percent, MAX(u.last_login_at) AS last_active FROM class_members cm JOIN faculty_classes fc ON fc.id=cm.class_id JOIN users u ON u.id=cm.student_id LEFT JOIN topic_progress tp ON tp.user_id=u.id WHERE fc.faculty_id=$1 GROUP BY u.id ORDER BY u.display_name`, [facultyId]); return { students: result.rows }; }
module.exports = { classOverview, listQuestions, saveQuestion, deleteQuestion, announce, csvReport, pdfReport };
