require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const lessonRoutes = require('./routes/lessons');
const progressRoutes = require('./routes/progress');
const authRoutes = require('./routes/auth');
const profileRoutes = require('./routes/profile');
const adminRoutes = require('./routes/admin');
const quantumRoutes = require('./routes/quantum');
const chatRoutes = require('./routes/chat');
const learningIntelligenceRoutes = require('./routes/learningIntelligence');
const quizAnalyticsRoutes = require('./routes/quizAnalytics');
const gamificationRoutes = require('./routes/gamification');
const analyticsRoutes = require('./routes/analytics');
const facultyRoutes = require('./routes/faculty');
const facultyStudentsRoutes = require('./routes/facultyStudents');
const errorHandler = require('./middleware/errorHandler');

const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json());
app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'quantum-atlas-api' }));
app.use('/api/auth', authRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/quantum', quantumRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/learning-intelligence', learningIntelligenceRoutes);
app.use('/api/quiz-analytics', quizAnalyticsRoutes);
app.use('/api/gamification', gamificationRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/faculty', facultyRoutes);
app.use('/api/faculty/students', facultyStudentsRoutes);
app.use('/api/lessons', lessonRoutes);
app.use('/api/progress', progressRoutes);
app.use(errorHandler);

const port = process.env.PORT || 5000;
if (require.main === module) app.listen(port, () => console.log(`API listening on ${port}`));
module.exports = app;
