import React, { useEffect, useMemo, useState } from 'react';
import FloatingCard from './FloatingCard';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';
export default function FacultyStudentDetail({ student, session, onClose }) {
  const [data, setData] = useState(null);
  const [message, setMessage] = useState('');
  const [status, setStatus] = useState('');
  const headers = useMemo(() => ({ Authorization: `Bearer ${session?.accessToken}`, 'Content-Type': 'application/json' }), [session?.accessToken]);
  useEffect(() => { fetch(`${API_URL}/faculty/students/${student.id}`, { headers }).then((response) => response.json()).then(setData).catch(() => setStatus('Could not load student detail')); }, [student.id, headers]);
  async function send(event) { event.preventDefault(); const response = await fetch(`${API_URL}/faculty/students/${student.id}/messages`, { method: 'POST', headers, body: JSON.stringify({ message }) }); setStatus(response.ok ? 'Message sent to student.' : 'Message could not be sent.'); if (response.ok) setMessage(''); }
  async function download(format) { const response = await fetch(`${API_URL}/faculty/students/${student.id}/report.${format}`, { headers }); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${student.display_name}-progress.${format}`; link.click(); URL.revokeObjectURL(url); }
  return <section className="student-detail"><div className="student-detail-heading"><div><p className="eyebrow">Learner profile</p><h2>{student.display_name}</h2><span className="muted">{student.email}</span></div><button className="text-button" type="button" onClick={onClose}>Close detail</button></div>{!data ? <p className="muted">Loading learner signals...</p> : <div className="student-detail-grid"><FloatingCard><p className="eyebrow">Learning timeline</p>{data.timeline.map((item, index) => <div className="timeline-item" key={`${item.created_at}-${index}`}><span className="timeline-dot" /><div><strong>{item.topic_slug.replaceAll('-', ' ')}</strong><small>{Math.round(item.score)}% score · {new Date(item.created_at).toLocaleDateString()}</small></div></div>)}</FloatingCard><FloatingCard><p className="eyebrow">Time analysis</p>{data.timeByTopic.map((item) => <div className="detail-time-row" key={item.topic_slug}><span>{item.topic_slug.replaceAll('-', ' ')}</span><strong>{Math.round(item.seconds / 60)} min</strong></div>)}</FloatingCard><FloatingCard><p className="eyebrow">Topics struggled with</p>{data.misconceptions.map((item) => <div className="detail-misconception" key={item.misconception_key}><span>{item.misconception_key.replaceAll('-', ' ')}</span><strong>{item.occurrences} signals</strong></div>)}{!data.misconceptions.length && <p className="muted">No detected misconceptions yet.</p>}</FloatingCard><FloatingCard><p className="eyebrow">Recommended interventions</p>{data.interventions.map((item) => <div className="intervention-row" key={item.misconception}>↗ {item.message}</div>)}{!data.interventions.length && <p className="muted">No intervention needed right now.</p>}</FloatingCard></div>}<div className="student-detail-actions"><button className="download-report" type="button" onClick={() => download('csv')}>Export CSV ↓</button><button className="download-report" type="button" onClick={() => download('pdf')}>Export PDF ↓</button><form onSubmit={send}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Send a personalized message..." required /><button className="btn-primary" type="submit">Send message →</button></form></div>{status && <p className="success-text">{status}</p>}</section>;
}
