import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';
export default function ProfilePage() {
  const { session, user, signOut } = useAuth();
  const [profile, setProfile] = useState(user);
  const [gamification, setGamification] = useState({ points: 0, level: { name: 'Beginner' }, badges: [], topicProgress: [] });
  const [message, setMessage] = useState('');
  useEffect(() => { const headers = { Authorization: `Bearer ${session.accessToken}` }; fetch(`${API_URL}/profile`, { headers }).then((response) => response.json()).then((body) => body.data && setProfile(body.data)); fetch(`${API_URL}/gamification/profile`, { headers }).then((response) => response.json()).then((body) => body.points !== undefined && setGamification(body)); }, [session]);
  async function save(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`${API_URL}/profile`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.accessToken}` }, body: JSON.stringify({ displayName: form.get('displayName'), bio: form.get('bio') }) }); const body = await response.json(); if (response.ok) { setProfile(body.data); setMessage('Profile updated'); } }
  return <main className="profile-shell page-enter"><div className="profile-header"><div><p className="eyebrow">Account / Profile</p><h1>Your learning identity</h1></div><button className="text-button" type="button" onClick={signOut}>Sign out</button></div>{gamification.badges.some((badge) => !badge.seen_at) && <div className="new-achievement" role="status"><span>✦</span><div><strong>New Achievement!</strong><p>You unlocked a new badge. Keep exploring.</p></div></div>}<div className="profile-gamification"><div className="profile-stat"><span className="muted">Points</span><strong>{gamification.points}</strong></div><div className="profile-stat"><span className="muted">Level</span><strong>{gamification.level.name}</strong></div><div className="profile-stat"><span className="muted">Badges</span><strong>{gamification.badges.length}</strong></div></div><form className="glassmorphism-card profile-card auth-form" onSubmit={save}><div className="profile-avatar">{(profile?.display_name || profile?.displayName || 'Q').slice(0, 1).toUpperCase()}</div><p className="role-badge">{profile?.role || 'student'}</p><label>Email<input value={profile?.email || ''} readOnly /></label><label>Display name<input name="displayName" defaultValue={profile?.display_name || profile?.displayName || ''} /></label><label>Bio<textarea name="bio" defaultValue={profile?.bio || ''} rows="4" placeholder="What are you exploring?" /></label>{message && <p className="success-text">{message}</p>}<button className="btn-primary auth-submit" type="submit">Save profile <span>→</span></button></form><section className="profile-section"><div className="section-heading"><div><p className="eyebrow">Your collection</p><h2>Achievements</h2></div></div><div className="badge-grid">{gamification.badges.map((badge) => <article className="badge-card glassmorphism-card" key={badge.key}><span className="badge-icon">{badge.icon}</span><div><h3>{badge.title}</h3><p className="muted">{badge.description}</p><small>+{badge.points_awarded} pts</small></div></article>)}</div></section><section className="profile-section"><div className="section-heading"><div><p className="eyebrow">Learning momentum</p><h2>Topic progress</h2></div></div><div className="topic-progress-list">{gamification.topicProgress.map((topic) => <div className="topic-progress-row" key={topic.topic_slug}><div><strong>{topic.topic_slug.replaceAll('-', ' ')}</strong><span>{Math.round(topic.completion_percent)}%</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${topic.completion_percent}%` }} /></div></div>)}</div></section></main>;
}
